[package]
name = "aoc_24"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort" # we don't need no panic-handling

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang/compiler-builtins"
